#!/bin/bash
#SBATCH -J test               # Job name
#SBATCH -o job.%j.out         # Name of stdout output file (%j expands to jobId)
#SBATCH -N 1                  # Total number of nodes requested
#SBATCH -n 8                # Total number of mpi tasks requested
#SBATCH -t 02:00:00           # Run time (hh:mm:ss) - 1.5 hours
#SBATCH -p mi1008x            # Desired partition


#peer, blocks, threads, iter
#ROC_SHMEM_NUM_BLOCK=4 srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 4 1024 1
#ROC_SHMEM_NUM_BLOCK=4 srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 4 1024 2
#ROC_SHMEM_NUM_BLOCK=4 srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 4 1024 4
#ROC_SHMEM_NUM_BLOCK=4 srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 4 1024 8
#ROC_SHMEM_NUM_BLOCK=4 srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 4 1024 10
ROC_SHMEM_NUM_BLOCK=4 srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 4 1024 100
