#!/bin/bash
#SBATCH -J test               # Job name
#SBATCH -o job.%j.out         # Name of stdout output file (%j expands to jobId)
#SBATCH -N 1                  # Total number of nodes requested
#SBATCH -n 8                # Total number of mpi tasks requested
#SBATCH -t 00:30:00           # Run time (hh:mm:ss) - 1.5 hours
#SBATCH -p mi1008x            # Desired partition


#peer, blocks, threads, iter
module use /share/bpotter/modulefiles/
module load rocshmem/1.6.3
module list

blocks=(8)
threads=(512)
iters=(1000)

for myblock in ${blocks[@]}
do 
	for mythread in ${threads[@]}
	do
		for myiter in ${iters[@]}
		do
			echo $myblock, $mythread, $myiter
			#srun -N1 -n8 -c4 ./shmem_putfence_bw_loopallgpu 1 ${myblock} ${mythread} ${myiter} |& tee log_putfence_B${myblock}_T${mythread}_I${myiter}
			srun -N1 -n8 -c4 ./shmem_putfencesig_bw_loopallgpu 1 ${myblock} ${mythread} ${myiter} |& tee log_putfencesig_B${myblock}_T${mythread}_I${myiter}
			#srun -N1 -n8 -c4 ./shmem_put_bw_loopallgpu 1 ${myblock} ${mythread} ${myiter} |& tee log_put_B${myblock}_T${mythread}_I${myiter} 
		done
	done
done
